heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a MySQL Slave node

parameters:

  slave_hostname:
    label: Slave Hostnames
    description: MySQL Slave node hostnames
    type: string
    default: mysql-slave

  image:
    label: Operating System
    description: |
      Server image used for all servers that are created as a part of this
      deployment
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      description: Must be a supported operating system.

  flavor:
    label: Server Size
    description: |
      Rackspace Cloud Server flavor to use. The size is based on the amount of
      RAM for the provisioned server.
    type: string
    default: 2 GB General Purpose v1
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
      - 15 GB I/O v1
      - 30 GB I/O v1
      - 512MB Standard Instance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  kitchen:
    label: Kitchen
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rackspace-orchestration-templates/mysql-multi

  chef_version:
    label: Chef Version
    description: Version of chef client to use
    type: string
    default: 11.12.8

  mysql_root_password:
    type: string

  mysql_repl_password:
    type: string

  mysql_debian_password:
    type: string

  master:
    type: string
    description: MySQL master server

  # SSH Keypair naming
  ssh_keypair_name:
    description: "keypair name to register with Nova for the root SSH key"
    type: string

  ssh_public_key:
    type: string

  ssh_private_key:
    type: string

  parent_stack_id:
    type: string

resources:
  slave_server:
    type: "OS::Nova::Server"
    properties:
      name: { get_param: slave_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: ssh_keypair_name }
      metadata:
        rax-heat: { get_param: parent_stack_id }

  slave_server_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: slave_server
    properties:
      username: root
      private_key: { get_param: ssh_private_key }
      host: { get_attr: [slave_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        mysql:
          server_root_password: { get_param: mysql_root_password }
          server_debian_password: { get_param: mysql_debian_password }
          server_repl_password: { get_param: mysql_repl_password }
          root_network_acl: ['127.0.0.1', 'localhost']
        mysql-multi:
          master: { get_param: master }
        rax:
          firewall:
            tcp:
              - 3306
        run_list: ["recipe[apt]",
                   "recipe[mysql::server]",
                   "recipe[mysql-multi::mysql_slave]",
                   "recipe[rax-firewall]"]

outputs:
  privateIPv4:
    description: Server Private IP
    value: { get_attr: [slave_server, networks, private, 0] }

  accessIPv4:
    description: Server Public IP
    value: { get_attr: [slave_server, accessIPv4] }
